'use client'

import { useState, useRef, useEffect, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import { Upload, Sparkles, Copy, ExternalLink, RefreshCw, X, ArrowLeft, Settings } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'

type Platform = 'instagram' | 'tiktok'

function PostPageInner() {
  const searchParams = useSearchParams()
  const [platform, setPlatform] = useState<Platform>((searchParams.get('platform') as Platform) || 'instagram')
  const [imageUrl, setImageUrl] = useState<string | null>(null)
  const [brief, setBrief] = useState(searchParams.get('brief') || '')
  const [caption, setCaption] = useState('')
  const [hashtags, setHashtags] = useState<string[]>([])
  const [hook, setHook] = useState('')
  const [cta, setCta] = useState('')
  const [seoScore, setSeoScore] = useState('')
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [hasKB, setHasKB] = useState(false)
  const [errorMsg, setErrorMsg] = useState('')
  const [imageBase64, setImageBase64] = useState<string | null>(null)
  const [imageMediaType, setImageMediaType] = useState<string>('image/jpeg')
  const [analyzing, setAnalyzing] = useState(false)
  const [imageDesc, setImageDesc] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  const autoGenerated = useRef(false)

  useEffect(() => {
    fetch('/api/social/kb').then(r => r.json()).then(kb => {
      setHasKB(!!(kb.brandName || kb.instagramHashtags?.length))
    })
  }, [])

  // No auto-generate on load — wait for image analysis to complete first

  function handleFile(file: File) {
    setImageUrl(URL.createObjectURL(file))
    setCaption(''); setHashtags([]); setHook(''); setCta(''); setImageDesc('')

    const reader = new FileReader()
    reader.onload = async (e) => {
      const dataUrl = e.target?.result as string
      const base64 = dataUrl.split(',')[1]
      const mt = file.type || 'image/jpeg'
      setImageBase64(base64)
      setImageMediaType(mt)

      setAnalyzing(true)
      try {
        const res = await fetch('/api/social/analyze-image', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ imageBase64: base64, mediaType: mt }),
        })
        const data = await res.json()
        if (data.description) {
          setImageDesc(data.description)
          // Pass description directly — state not yet flushed
          generate(data.description)
        }
      } catch {
        // silent
      } finally {
        setAnalyzing(false)
      }
    }
    reader.readAsDataURL(file)
  }

  async function generate(descOverride?: string) {
    setLoading(true)
    setErrorMsg('')
    try {
      const res = await fetch('/api/social/generate-post', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ platform, brief, imageContext: descOverride ?? imageDesc }),
      })
      const data = await res.json()
      if (!res.ok) {
        setErrorMsg(data.error || `Fehler ${res.status}`)
        return
      }
      setCaption(data.caption || '')
      setHashtags(data.hashtags || [])
      setHook(data.hook || '')
      setCta(data.cta || '')
      setSeoScore(data.seoScore || '')
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : 'Netzwerkfehler')
    } finally {
      setLoading(false)
    }
  }

  function copyAll() {
    const text = `${caption}\n\n${hashtags.map(h => `#${h.replace('#', '')}`).join(' ')}`
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function openPlatform() {
    copyAll()
    window.open(platform === 'instagram' ? 'https://www.instagram.com/create/style/' : 'https://www.tiktok.com/upload', '_blank')
  }

  const fullText = caption + (hashtags.length ? '\n\n' + hashtags.map(h => `#${h.replace('#', '')}`).join(' ') : '')

  return (
    <main className="min-h-screen bg-[#0a0a0f]">
      <div className="w-full max-w-6xl mx-auto px-4 py-8 space-y-5">

        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/" className="text-slate-500 hover:text-slate-300 transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <h1 className="text-xl font-semibold text-slate-100 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-pink-400" /> Post erstellen
            </h1>
          </div>
          <div className="flex items-center gap-3">
            {!hasKB && (
              <Link href="/social-settings" className="text-xs text-yellow-400 hover:text-yellow-300 flex items-center gap-1">
                <Settings className="w-3.5 h-3.5" /> Wissensdatenbank einrichten
              </Link>
            )}
            <div className="flex rounded-lg overflow-hidden border border-white/10">
              {(['instagram', 'tiktok'] as Platform[]).map(p => (
                <button key={p} onClick={() => setPlatform(p)}
                  className={`px-4 py-1.5 text-sm transition-colors ${platform === p ? 'bg-pink-500/20 text-pink-300' : 'text-slate-500 hover:text-slate-300'}`}>
                  {p === 'instagram' ? '📸 Instagram' : '♪ TikTok'}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Bild Upload — volle Breite */}
        <div
          onDrop={e => { e.preventDefault(); const f = e.dataTransfer.files[0]; if (f) handleFile(f) }}
          onDragOver={e => e.preventDefault()}
          onClick={() => !imageUrl && fileRef.current?.click()}
          className={`relative w-full rounded-2xl overflow-hidden bg-black/20 border-2 border-dashed transition-colors ${imageUrl ? 'border-transparent cursor-default' : 'border-white/10 hover:border-pink-500/40 cursor-pointer'}`}
          style={{ minHeight: imageUrl ? 420 : 200 }}
        >
          {imageUrl ? (
            <>
              <Image src={imageUrl} alt="Vorschau" fill className="object-contain" unoptimized />
              <button
                onClick={e => { e.stopPropagation(); setImageUrl(null); setImageBase64(null); setImageDesc('') }}
                className="absolute top-4 right-4 bg-black/70 rounded-full p-2 hover:bg-black/90 z-10 transition-colors"
              >
                <X className="w-4 h-4 text-white" />
              </button>
              {analyzing && (
                <div className="absolute bottom-4 left-4 flex items-center gap-2 bg-black/80 rounded-xl px-4 py-2 z-10">
                  <RefreshCw className="w-3.5 h-3.5 text-pink-400 animate-spin" />
                  <span className="text-xs text-pink-300">KI analysiert Bild...</span>
                </div>
              )}
              {imageDesc && !analyzing && (
                <div className="absolute bottom-4 left-4 flex items-center gap-2 bg-black/80 rounded-xl px-4 py-2 z-10">
                  <span className="text-xs text-green-400">✓ Bild analysiert — Caption wird darauf basieren</span>
                </div>
              )}
              {/* Klick zum Ändern */}
              <button
                onClick={e => { e.stopPropagation(); fileRef.current?.click() }}
                className="absolute top-4 left-4 bg-black/70 rounded-xl px-3 py-1.5 text-xs text-slate-300 hover:bg-black/90 z-10 transition-colors"
              >
                Bild ändern
              </button>
            </>
          ) : (
            <div className="flex flex-col items-center justify-center h-full py-14 gap-3">
              <Upload className="w-10 h-10 text-slate-600" />
              <p className="text-base text-slate-500">Bild oder Video hierher ziehen</p>
              <p className="text-sm text-slate-700">oder klicken zum Auswählen</p>
            </div>
          )}
        </div>
        <input ref={fileRef} type="file" accept="image/*,video/*" className="hidden"
          onChange={e => { const f = e.target.files?.[0]; if (f) handleFile(f) }} />

        {/* Generieren Button */}
        <button
          onClick={generate}
          disabled={loading || analyzing}
          className="w-full flex items-center justify-center gap-2 py-4 bg-pink-500/20 hover:bg-pink-500/30 text-pink-300 rounded-xl text-base font-medium transition-colors disabled:opacity-40"
        >
          {loading ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
          {loading ? 'Generiere optimalen Post...' : analyzing ? 'Warte auf Bild-Analyse...' : 'Post generieren'}
        </button>

        {errorMsg && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-xl px-4 py-3 text-sm text-red-400">
            {errorMsg}
          </div>
        )}

        {/* Ergebnis — volle Breite, von oben nach unten */}
        {hook && (
          <div className="bg-pink-500/10 border border-pink-500/20 rounded-xl px-5 py-4">
            <p className="text-[10px] text-pink-500/60 uppercase tracking-widest mb-2">Hook</p>
            <p className="text-base text-pink-200 font-medium">{hook}</p>
          </div>
        )}

        {caption && (
          <div>
            <div className="flex items-center justify-between mb-2">
              <p className="text-xs text-slate-500 uppercase tracking-widest">Caption</p>
              {seoScore && <span className="text-xs text-green-400">SEO Score: {seoScore}/10</span>}
            </div>
            <textarea
              value={caption}
              onChange={e => setCaption(e.target.value)}
              rows={6}
              className="w-full bg-black/20 border border-white/10 rounded-xl px-5 py-4 text-sm text-slate-200 focus:outline-none focus:border-pink-500/40 resize-none leading-relaxed"
            />
          </div>
        )}

        {hashtags.length > 0 && (
          <div>
            <p className="text-xs text-slate-500 uppercase tracking-widest mb-3">Hashtags ({hashtags.length})</p>
            <div className="flex flex-wrap gap-2">
              {hashtags.map((tag, i) => (
                <span key={i} className="text-sm px-3 py-1 rounded-full bg-pink-500/10 text-pink-400 border border-pink-500/20">
                  #{tag.replace('#', '')}
                </span>
              ))}
            </div>
          </div>
        )}

        {cta && (
          <div className="bg-cyan-500/10 border border-cyan-500/20 rounded-xl px-5 py-4">
            <p className="text-[10px] text-cyan-500/60 uppercase tracking-widest mb-2">Call-to-Action</p>
            <p className="text-sm text-cyan-200">{cta}</p>
          </div>
        )}

        {fullText.trim() && (
          <div className="flex gap-3 pt-2 pb-8">
            <button
              onClick={copyAll}
              className="flex-1 flex items-center justify-center gap-2 py-3.5 bg-white/5 hover:bg-white/10 text-slate-300 rounded-xl text-sm transition-colors"
            >
              <Copy className="w-4 h-4" />
              {copied ? '✓ Kopiert!' : 'Alles kopieren'}
            </button>
            <button
              onClick={openPlatform}
              className="flex-1 flex items-center justify-center gap-2 py-3.5 bg-pink-500/20 hover:bg-pink-500/30 text-pink-300 rounded-xl text-sm font-medium transition-colors"
            >
              <ExternalLink className="w-4 h-4" />
              {platform === 'instagram' ? '→ Instagram öffnen' : '→ TikTok öffnen'}
            </button>
          </div>
        )}
      </div>
    </main>
  )
}

export default function PostPage() {
  return (
    <Suspense>
      <PostPageInner />
    </Suspense>
  )
}
